### PR TITLE
Keep a consistant order for hashes for get_package_hashes.

### LINKED ISSUE #126: Order of hashes from `get_package_hashes`
As in #105 , I wonder if we could expect the output of `get_package_hashes` to have hashes in lexicographical order.

GitHub's dependabot is relying on that and is creating commits in my repo that are conflicting with other tools. Of course dependabot could fix it, but I believe it would be cleaner to have the same order out of `get_package_hashes` than the one done by `run_packages`.

### PR DESCRIPTION
**Pull request by pcorpet**
Fixes #126

### CODE REVIEW

**Comment by MarkusH** [comment]
This change raises an error for me on Python 3.9 and 3.10:

```bash
$ python -m hashin -r requirements.txt django
```
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/markus/Coding/hashin/hashin.py", line 855, in <module>
    sys.exit(main())
  File "/home/markus/Coding/hashin/hashin.py", line 837, in main
    return run(
  File "/home/markus/Coding/hashin/hashin.py", line 135, in run
    return run_packages(specs, requirements_file, *args, **kwargs)
  File "/home/markus/Coding/hashin/hashin.py", line 249, in run_packages
    for i, release in enumerate(data["hashes"], key=lambda r: r["hash"]):
TypeError: 'key' is an invalid keyword argument for enumerate()
```
```bash
$ hashin -r requirements.txt django
```
```python
Traceback (most recent call last):
  File "/home/markus/Coding/hashin/venv39/bin/hashin", line 33, in <module>
    sys.exit(load_entry_point('hashin', 'console_scripts', 'hashin')())
  File "/home/markus/Coding/hashin/hashin.py", line 837, in main
    return run(
  File "/home/markus/Coding/hashin/hashin.py", line 135, in run
    return run_packages(specs, requirements_file, *args, **kwargs)
  File "/home/markus/Coding/hashin/hashin.py", line 249, in run_packages
    for i, release in enumerate(data["hashes"], key=lambda r: r["hash"]):
TypeError: 'key' is an invalid keyword argument for enumerate()
```

**Comment by pcorpet** [comment]
Oops, I was sloppy, sorry about that.

**Comment by MarkusH** [comment]
Works for me. Thank you!

**Comment by peterbe** [comment]
@pcorpet 
Would you mind editing the matrix in `.github/workflows/python.yml` and the Python version lists in `tox.ini` as part of this PR?

**Comment by peterbe** [comment]
In fact, perhaps it would be best to move the other linting tasks that, currently, 3.8 does into 3.10 in the tox file.

**Review by peterbe — CHANGES_REQUESTED** [review]
Great work!!
But because of the comments from @MarkusH that it, did behave differently in 3.9 and 3.10 I would not feel confident merging this till we have 3.9 and 3.10 in the test matrix. 

As mentioned, I'm cool with you adding that into this PR if it's a bit impure. Or, if you want to put up a quick PR to just add 3.9 and 3.10 to the tests first, I'm happy to merge that quickly.

**Comment by pcorpet** [comment]
@peterbe it was actually failing on all versions before my fixes. But I'm all for clean commits and PRs so I'll send you another PR.

**Comment by pcorpet** [comment]
I also realize I forgot to update the version history...

**Review by MarkusH — APPROVED** [review]
Nice!

**Comment by pcorpet** [comment]
I've rebased so that CI runs on python 3.9 and 3.10: ready to merge.

**Review by peterbe — APPROVED** [review]

**Pull request merged**
