### PR TITLE
Preserve indented comments

### LINKED ISSUE #124: hashin removes # when hashes were generated with pip-compile
Looks like `hashin` removes `#` when hashes were generated with `pip-compile` originally. Example 

```
-requests==2.25.1 \
-    --hash=sha256:27973dd4a904a4f13b263a19c866c13b92a39ed1c964655f025f3f8d3d75b804 \
-    --hash=sha256:c210084e36a42ae6b9219e00e48287def368a26d03a048ddad7bfee44f75871e
-    # via -r project/requirements.in
+requests==2.22.0 \
+    --hash=sha256:11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4 \
+    --hash=sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31
```

### PR DESCRIPTION
**Pull request by MarkusH**
Fixes #124

### CODE REVIEW

**Comment by alaamub** [comment]
Is this going to be merged soob?

**Comment by peterbe** [comment]
Trying to force the Actions to run.

**Comment by peterbe** [comment]
Weird. Why aren't Actions run? I don't get it. Your PR was created *after* the `.github/workflows/python.yml` file was created.

**Comment by peterbe** [comment]
> Weird. Why aren't Actions run? I don't get it. Your PR was created _after_ the `.github/workflows/python.yml` file was created.

Figured it out! I'll make a PR to fix that. One sec.

**Comment by peterbe** [comment]
@MarkusH Can you merge in the latest `master` into your branch now? 
Thanks to https://github.com/peterbe/hashin/pull/127 test should run on your PR then.

**Comment by MarkusH** [comment]
Thank you, @peterbe! I rebased and force-pushed.

**Pull request merged**
