### PR TITLE
update deploy script

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
@hartwork is this correct?
Seems to have worked when I uploaded 1.0.2.

**Comment by hartwork** [comment]
> @hartwork is this correct? Seems to have worked when I uploaded 1.0.2.

@peterbe I'm not 100% sure about `--repository <name>` but `default: pypi` in `twine upload --help` makes me think dropping it is probably a good move.

`twine upload dist/*` is probably asking for trouble though: I'm expecting this to upload any new files that lay around there from some random experiment on say a dev branch; the asterisk is way to greedy for me to feel safe, and I have seen people upload wheels for older(1) releases when doing a new release, and the results were not pretty…

**Comment by peterbe** [comment]
> asking for trouble though: I'm expecting this to upload any new files that lay around there

See [line 6](https://github.com/peterbe/hashin/pull/189/files#diff-30883d1df2fc62f59d66255a70dc05f60d3d4ef4d3957e6e3e38e62f6e471bd0R6).

**Review by hartwork — APPROVED** [review]
> > asking for trouble though: I'm expecting this to upload any new files that lay around there
> 
> See [line 6](https://github.com/peterbe/hashin/pull/189/files#diff-30883d1df2fc62f59d66255a70dc05f60d3d4ef4d3957e6e3e38e62f6e471bd0R6).

@peterbe fair point :smile:

**Pull request merged**
