### PR TITLE
Fix function `expand_python_version` for "3.10" and upwards (fixes #184)

### LINKED ISSUE #184: Running hashin with Python versions >= 3.10 raises PackageError('No releases can be found....')
The issue seems to stem from this piece of code.

```python
def expand_python_version(version):
    if not re.match(r"^\d\.\d$", version):
        return [version]
```

The above regular expression assumes the minor version number can have only a single digit. Therefore the result will be incorrect for Python versions >= 3.10.

We probably want to change it to

```python
    if not re.match(r"^\d\.\d*\d$", version)
```

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #184

CC @vishnuwazoku @peterbe

### CODE REVIEW

**Review by vishnuwazoku — APPROVED** [review]

**Review by peterbe — APPROVED** [review]

**Comment by hartwork** [comment]
@peterbe is there chance that you could cut a new release 1.0.2 with this fix?

**Comment by hartwork** [comment]
@vishnuwazoku thanks for the testing and/or review! :+1:

**Comment by peterbe** [comment]
> @peterbe is there chance that you could cut a new release 1.0.2 with this fix?

Since I changed computer I lost my `.pypirc` file and I don't know how to create it or combine it with `twine`. .

**Comment by hartwork** [comment]
@peterbe should we jump on a voice call about it some time?

PS:
```console
# cat ~/.pypirc 
[pypi]
username = __token__
password = CENSORED
```

PPS: `# twine upload dist/*5.1.0*`

**Comment by peterbe** [comment]
It's been so long since I did this! :)

```
❯ cat ~/.pypirc
[distutils]
index-servers =
    pypi

[pypi]
username = __token__
password = xxxxxxxxxxx
```

and 
```
❯ rm -fr dist/
❯ python setup.py sdist bdist_wheel
❯ ls -l dist
total 72
-rw-r--r--  1 peterbe  staff  16356 Sep 23 17:55 hashin-1.0.2-py2.py3-none-any.whl
-rw-r--r--  1 peterbe  staff  17052 Sep 23 17:55 hashin-1.0.2.tar.gz
```
lastly

```
❯ twine upload dist/
Uploading distributions to https://upload.pypi.org/legacy/
ERROR    InvalidDistribution: Unknown distribution format: ''

```

**Comment by hartwork** [comment]
> ```
> ❯ twine upload dist/
> Uploading distributions to https://upload.pypi.org/legacy/
> ERROR    InvalidDistribution: Unknown distribution format: ''
> ```

@peterbe passing the the whole folder would be dangerous anyway (i.e. doing too much next time) but it seems you need **filenames** rather than folders anyway as per https://stackoverflow.com/a/65369679 . So `twine upload dist/*1.0.2*` is what I recommend.

**Comment by peterbe** [comment]
That seems to have worked. 
https://pypi.org/project/hashin/1.0.2/

**Comment by hartwork** [comment]
@peterbe awesome, thank you! :+1:

**Pull request merged**
